
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 09 18:11:31 CET 2026
//----------------------------------------------------

package com.mycompany.errorcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 12;
  public static final int NE = 26;
  public static final int LT = 23;
  public static final int SEMICOLON = 20;
  public static final int SELECT = 9;
  public static final int OR = 11;
  public static final int CHAR = 6;
  public static final int LEFTPAR = 15;
  public static final int END = 4;
  public static final int RIGHTPAR = 16;
  public static final int GT = 27;
  public static final int COLON = 17;
  public static final int LE = 24;
  public static final int ID = 13;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int BOOLEAN = 8;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int GE = 28;
  public static final int ARROW = 22;
  public static final int DOT = 19;
  public static final int CONST = 14;
  public static final int CASE = 10;
  public static final int error = 1;
  public static final int EQ = 25;
  public static final int ASSIGN = 21;
  public static final int INTEGER = 5;
  public static final int REAL = 7;
}

